---
title: "Project using Human Activity Recognition Using Smartphones Dataset"
author: "suresh joshi"
date: "September 27, 2015"
output: html_document
---

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean



For additional info about the collected variables please refer to feature_info.txt file found in https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

This project Extracts variable containing mean and standard deviation for each measurement and produce averages of each of those measures after
grouping them into subject and activity. Below is the variable in subject_averages.txt file.

Variables:
=========
1.  activity                             | Factor w/ 6 levels "WALKING","WALKING_UPSTAIRS",..: 1 1 1 1 1 1 1 1 1 1 ...
2.  subject                              | Factor w/ 30 levels "1","3","5","6",..: 1 2 3 4 5 6 7 8 9 10 ...
3.  tBodyAcc-mean()-X                    | num  0.277 0.276 0.278 0.284 0.276 ...
4.  tBodyAcc-mean()-Y                    | num  -0.0174 -0.0172 -0.0173 -0.0169 -0.0187 ...
5.  tBodyAcc-mean()-Z                    | num  -0.111 -0.113 -0.108 -0.11 -0.111 ...
6.  tBodyAcc-std()-X                     | num  -0.284 -0.36 -0.294 -0.297 -0.327 ...
7.  tBodyAcc-std()-Y                     | num  0.1145 -0.0699 0.0767 0.1642 -0.0773 ...
8.  tBodyAcc-std()-Z                     | num  -0.26 -0.387 -0.457 -0.504 0.16 ...
9.  tGravityAcc-mean()-X                 | num  0.935 0.937 0.973 0.958 0.933 ...
10.  tGravityAcc-mean()-Y                | num  -0.282 -0.262 -0.1 -0.215 -0.159 ...
11.  tGravityAcc-mean()-Z                | num  -0.0681 -0.13811 0.00248 0.03319 -0.16085 ...
12.  tGravityAcc-std()-X                 | num  -0.977 -0.978 -0.979 -0.978 -0.98 ...
13.  tGravityAcc-std()-Y                 | num  -0.971 -0.962 -0.962 -0.964 -0.969 ...
14.  tGravityAcc-std()-Z                 | num  -0.948 -0.952 -0.965 -0.957 -0.952 ...
15.  tBodyAccJerk-mean()-X               | num  0.074 0.0815 0.0846 0.07 0.0901 ...
16.  tBodyAccJerk-mean()-Y               | num  0.0283 0.0101 -0.0163 -0.0165 0.0184 ...
17.  tBodyAccJerk-mean()-Z               | num  -4.17e-03 -5.62e-03 8.32e-05 -7.39e-03 -2.10e-02 ...
18.  tBodyAccJerk-std()-X                | num  -0.114 -0.269 -0.303 -0.133 -0.346 ...
19.  tBodyAccJerk-std()-Y                | num  0.067 -0.04496 -0.09104 0.00809 -0.05474 ...
20.  tBodyAccJerk-std()-Z                | num  -0.503 -0.529 -0.613 -0.576 -0.149 ...
21.  tBodyGyro-mean()-X                  | num  -0.04183 -0.02564 -0.04889 -0.02551 0.00229 ...
22.  tBodyGyro-mean()-Y                  | num  -0.0695 -0.0779 -0.069 -0.0744 -0.0837 ...
23.  tBodyGyro-mean()-Z                  | num  0.0849 0.0813 0.0815 0.0839 0.0641 ...
24.  tBodyGyro-std()-X                   | num  -0.474 -0.572 -0.491 -0.446 -0.503 ...
25.  tBodyGyro-std()-Y                   | num  -0.0546 -0.5638 -0.5046 -0.3317 -0.2311 ...
26.  tBodyGyro-std()-Z                   | num  -0.344 -0.477 -0.319 -0.383 -0.396 ...
27.  tBodyGyroJerk-mean()-X              | num  -0.09 -0.0952 -0.0888 -0.0879 -0.1237 ...
28.  tBodyGyroJerk-mean()-Y              | num  -0.0398 -0.0388 -0.045 -0.0362 -0.0448 ...
29.  tBodyGyroJerk-mean()-Z              | num  -0.0461 -0.0504 -0.0483 -0.054 -0.0496 ...
30.  tBodyGyroJerk-std()-X               | num  -0.207 -0.386 -0.358 -0.183 -0.212 ...
31.  tBodyGyroJerk-std()-Y               | num  -0.304 -0.639 -0.571 -0.416 -0.174 ...
32.  tBodyGyroJerk-std()-Z               | num  -0.404 -0.537 -0.158 -0.167 -0.458 ...
33.  tBodyAccMag-mean()                  | num  -0.137 -0.2547 -0.1583 -0.1668 -0.0978 ...
34.  tBodyAccMag-std()                   | num  -0.22 -0.328 -0.377 -0.267 -0.199 ...
35.  tGravityAccMag-mean()               | num  -0.137 -0.2547 -0.1583 -0.1668 -0.0978 ...
36.  tGravityAccMag-std()                | num  -0.22 -0.328 -0.377 -0.267 -0.199 ...
37.  tBodyAccJerkMag-mean()              | num  -0.141 -0.28 -0.288 -0.195 -0.193 ...
38.  tBodyAccJerkMag-std()               | num  -0.0745 -0.1399 -0.2822 -0.0706 -0.0276 ...
39.  tBodyGyroMag-mean()                 | num  -0.161 -0.466 -0.356 -0.281 -0.306 ...
40.  tBodyGyroMag-std()                  | num  -0.187 -0.562 -0.492 -0.366 -0.198 ...
41.  tBodyGyroJerkMag-mean()             | num  -0.299 -0.566 -0.445 -0.321 -0.3 ...
42.  tBodyGyroJerkMag-std()              | num  -0.3253 -0.5674 -0.4892 -0.3647 -0.0953 ...
43.  fBodyAcc-mean()-X                   | num  -0.203 -0.317 -0.288 -0.188 -0.343 ...
44.  fBodyAcc-mean()-Y                   | num  0.08971 -0.0813 0.00946 0.14078 -0.06416 ...
45.  fBodyAcc-mean()-Z                   | num  -0.3316 -0.4124 -0.4903 -0.4985 0.0386 ...
46.  fBodyAcc-std()-X                    | num  -0.319 -0.379 -0.298 -0.345 -0.322 ...
47.  fBodyAcc-std()-Y                    | num  0.056 -0.124 0.0426 0.1017 -0.1437 ...
48.  fBodyAcc-std()-Z                    | num  -0.28 -0.423 -0.483 -0.55 0.133 ...
49.  fBodyAcc-meanFreq()-X               | num  -0.208 -0.247 -0.322 -0.197 -0.314 ...
50.  fBodyAcc-meanFreq()-Y               | num  0.11309 0.17174 -0.00204 0.02207 0.16043 ...
51.  fBodyAcc-meanFreq()-Z               | num  0.0497 0.0749 0.0247 0.1851 0.1246 ...
52.  fBodyAccJerk-mean()-X               | num  -0.171 -0.305 -0.345 -0.151 -0.384 ...
53.  fBodyAccJerk-mean()-Y               | num  -0.0352 -0.1405 -0.1811 -0.0754 -0.1232 ...
54.  fBodyAccJerk-mean()-Z               | num  -0.469 -0.514 -0.59 -0.541 -0.106 ...
55.  fBodyAccJerk-std()-X                | num  -0.134 -0.297 -0.321 -0.193 -0.365 ...
56.  fBodyAccJerk-std()-Y                | num  0.10674 -0.00561 -0.05452 0.03145 -0.04319 ...
57.  fBodyAccJerk-std()-Z                | num  -0.535 -0.544 -0.633 -0.609 -0.191 ...
58.  fBodyAccJerk-meanFreq()-X           | num  -0.209 -0.216 -0.359 -0.178 -0.285 ...
59.  fBodyAccJerk-meanFreq()-Y           | num  -0.386 -0.259 -0.534 -0.466 -0.287 ...
60.  fBodyAccJerk-meanFreq()-Z           | num  -0.186 -0.347 -0.344 -0.104 -0.245 ...
61.  fBodyGyro-mean()-X                  | num  -0.339 -0.438 -0.373 -0.24 -0.318 ...
62.  fBodyGyro-mean()-Y                  | num  -0.103 -0.562 -0.514 -0.341 -0.152 ...
63.  fBodyGyro-mean()-Z                  | num  -0.256 -0.418 -0.213 -0.204 -0.367 ...
64.  fBodyGyro-std()-X                   | num  -0.517 -0.615 -0.529 -0.515 -0.564 ...
65.  fBodyGyro-std()-Y                   | num  -0.0335 -0.5689 -0.5027 -0.332 -0.2909 ...
66.  fBodyGyro-std()-Z                   | num  -0.437 -0.546 -0.42 -0.512 -0.463 ...
67.  fBodyGyro-meanFreq()-X              | num  0.0148 0.0338 -0.0459 0.0912 0.1119 ...
68.  fBodyGyro-meanFreq()-Y              | num  -0.0658 -0.038 -0.0192 0.0416 0.2731 ...
69.  fBodyGyro-meanFreq()-Z              | num  0.000773 -0.044508 0.167458 0.302875 0.014356 ...
70.  fBodyAccMag-mean()                  | num  -0.129 -0.29 -0.305 -0.201 -0.151 ...
71.  fBodyAccMag-std()                   | num  -0.398 -0.456 -0.52 -0.422 -0.352 ...
72.  fBodyAccMag-meanFreq()              | num  0.191 0.113 0.15 0.2 0.173 ...
73.  fBodyBodyAccJerkMag-mean()          | num  -0.0571 -0.1868 -0.2695 -0.0554 -0.0384 ...
74.  fBodyBodyAccJerkMag-std()           | num  -0.1035 -0.0899 -0.3057 -0.0965 -0.0221 ...
75.  fBodyBodyAccJerkMag-meanFreq()      | num  0.09382 -0.11716 -0.00497 -0.00923 -0.01274 ...
76.  fBodyBodyGyroMag-mean()             | num  -0.199 -0.57 -0.484 -0.33 -0.193 ...
77.  fBodyBodyGyroMag-std()              | num  -0.321 -0.633 -0.59 -0.511 -0.344 ...
78.  fBodyBodyGyroMag-meanFreq()         | num  0.269 0.181 0.251 0.293 0.3 ...
79.  fBodyBodyGyroJerkMag-mean()         | num  -0.319 -0.608 -0.548 -0.367 -0.155 ...
80.  fBodyBodyGyroJerkMag-std()          | num  -0.3816 -0.5491 -0.4557 -0.4081 -0.0842 ...
81.  fBodyBodyGyroJerkMag-meanFreq()     | num  0.19066 0.04576 0.05273 0.10092 0.00088 ...
82.  angle(tBodyAccMean,gravity)         | num  0.0605 0.0528 -0.0323 -0.068 -0.0236 ...
83.  angle(tBodyAccJerkMean),gravityMean)| num  -0.00793 -0.0763 -0.01172 0.0056 -0.00538 ...
84.  angle(tBodyGyroMean,gravityMean)    | num  0.0131 0.0968 0.0237 -0.0511 -0.0527 ...
85.  angle(tBodyGyroJerkMean,gravityMean)| num  -0.0187 -0.0367 -0.0349 -0.0819 0.0539 ...
86.  angle(X,gravityMean)                | num  -0.729 -0.723 -0.917 -0.806 -0.748 ...
87.  angle(Y,gravityMean)                | num  0.277 0.262 0.152 0.23 0.192 ...
88.  angle(Z,gravityMean)                | num  0.0689 0.1174 0.02 -0.0013 0.1354 ...
 

Activity levels
===============
		1 WALKING
		2 WALKING_UPSTAIRS
		3 WALKING_DOWNSTAIRS
		4 SITTING
		5 STANDING
		6 LAYING
		